### ISSUE TITLE
Project organization and some tips!

### ISSUE THREAD

**Issue by MoatazBadawy** [Passant-Hatem/NewsApp#1]
Hey Passant, Nice work you made there 👏

I made a new branch to organize your project, You could allow some modifications to your project so that you can receive any new pull requests 👍
I have some tips for you to improve your project:

- You would create a viewmodel for each fragment you have that make specific actions.
for example, you have a search fragment and a news fragment, so the search fragment will have its viewmodel and it is logical and the same thing for the search, Thus, your code will be organized and easy to modify later, and each class will do a specific function of its own 😉

- Try to use flow with room database and API, This will give you the ability to deal with data in the form of a stream and you can filter your data easily, as well as enjoy all the features of flow, it will be very useful for your application 😃

keep up the great work 💪

**Comment by Passant-Ahmed** [comment]
Thanks for your review 😃
I fixed the view model issue and I'm still working on the other issue
